import Layout from "@/components/global/Layout";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Mahrus Rohisyam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta name="viewport" content="viewport-fit=cover"></meta>
      <Layout>{children}</Layout>
    </html>
  );
}
